name: csafe_fitness
description: A dart implementation of the CSAFE protocol framework for fitness machines
version: 0.1.1
repository: https://github.com/CrewLAB/csafe-fitness

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  equatable: ^2.0.0

#   path: ^1.8.0

dev_dependencies:
  coverage: ^1.0.4
  lints: ^1.0.0
  test: ^1.16.0
